initdata()

function initdata(){
    if (!localStorage.cloth) {
        const cloth = [
            {id:"outfit1", src:"../assets/outfit/outfit1.png", clothClass:"outfit"},
            {id:"outfit2", src:"../assets/outfit/outfit2.png", clothClass:"outfit"},
            {id:"outfit3", src:"../assets/outfit/outfit3.png", clothClass:"outfit"},
            {id:"outfit4", src:"../assets/outfit/outfit4.png", clothClass:"outfit"},
            {id:"outfit5", src:"../assets/outfit/outfit5.png", clothClass:"outfit"},
            {id:"outfit6", src:"../assets/outfit/outfit6.png", clothClass:"outfit"},
            {id:"outfit7", src:"../assets/outfit/outfit7.png", clothClass:"outfit"},
            {id:"outfit8", src:"../assets/outfit/outfit8.png", clothClass:"outfit"},
            {id:"outfit9", src:"../assets/outfit/outfit9.png", clothClass:"outfit"},
            {id:"outfit10", src:"../assets/outfit/outfit10.png", clothClass:"outfit"},
            {id:"outfit11", src:"../assets/outfit/outfit11.png", clothClass:"outfit"},
            {id:"outfit12", src:"../assets/outfit/outfit12.png", clothClass:"outfit"},
            {id:"outfit13", src:"../assets/outfit/outfit13.png", clothClass:"outfit"},
            {id:"outfit14", src:"../assets/outfit/outfit14.png", clothClass:"outfit"},
            {id:"outfit15", src:"../assets/outfit/outfit15.png", clothClass:"outfit"},
            {id:"bottoms1", src:"../assets/bottoms/bottoms1.png", clothClass:"bottoms"},
            {id:"bottoms2", src:"../assets/bottoms/bottoms2.png", clothClass:"bottoms"},
            {id:"bottoms3", src:"../assets/bottoms/bottoms3.png", clothClass:"bottoms"},
            {id:"bottoms4", src:"../assets/bottoms/bottoms4.png", clothClass:"bottoms"},
            {id:"bottoms5", src:"../assets/bottoms/bottoms5.png", clothClass:"bottoms"},
            {id:"bottoms6", src:"../assets/bottoms/bottoms6.png", clothClass:"bottoms"},
            {id:"bottoms7", src:"../assets/bottoms/bottoms7.png", clothClass:"bottoms"},
            {id:"bottoms8", src:"../assets/bottoms/bottoms8.png", clothClass:"bottoms"},
            {id:"bottoms9", src:"../assets/bottoms/bottoms9.png", clothClass:"bottoms"},
            {id:"bottoms10", src:"../assets/bottoms/bottoms10.png", clothClass:"bottoms"},
            {id:"bottoms11", src:"../assets/bottoms/bottoms11.png", clothClass:"bottoms"},
            {id:"bottoms12", src:"../assets/bottoms/bottoms12.png", clothClass:"bottoms"},
            {id:"bottoms13", src:"../assets/bottoms/bottoms13.png", clothClass:"bottoms"},
            {id:"bottoms14", src:"../assets/bottoms/bottoms14.png", clothClass:"bottoms"},
            {id:"bottoms15", src:"../assets/bottoms/bottoms15.png", clothClass:"bottoms"},
            {id:"accessories1", src:"../assets/accessories/accessories1.png", clothClass:"accessories"},
            {id:"accessories2", src:"../assets/accessories/accessories2.png", clothClass:"accessories"},
            {id:"accessories3", src:"../assets/accessories/accessories3.png", clothClass:"accessories"},
            {id:"accessories4", src:"../assets/accessories/accessories4.png", clothClass:"accessories"},
            {id:"accessories5", src:"../assets/accessories/accessories5.png", clothClass:"accessories"},
            {id:"accessories6", src:"../assets/accessories/accessories6.png", clothClass:"accessories"},
            {id:"accessories7", src:"../assets/accessories/accessories7.png", clothClass:"accessories"},
            {id:"accessories8", src:"../assets/accessories/accessories8.png", clothClass:"accessories"},
            {id:"accessories9", src:"../assets/accessories/accessories9.png", clothClass:"accessories"},
            {id:"accessories10", src:"../assets/accessories/accessories10.png", clothClass:"accessories"},
            {id:"accessories11", src:"../assets/accessories/accessories11.png", clothClass:"accessories"},
            {id:"accessories12", src:"../assets/accessories/accessories12.png", clothClass:"accessories"},
            {id:"accessories13", src:"../assets/accessories/accessories13.png", clothClass:"accessories"},
            {id:"accessories14", src:"../assets/accessories/accessories14.png", clothClass:"accessories"},
            {id:"accessories15", src:"../assets/accessories/accessories15.png", clothClass:"accessories"},
            {id:"outerwear1", src:"../assets/outerwear/outerwear1.png", clothClass:"outerwear"},
            {id:"outerwear2", src:"../assets/outerwear/outerwear2.png", clothClass:"outerwear"},
            {id:"outerwear3", src:"../assets/outerwear/outerwear3.png", clothClass:"outerwear"},
            {id:"outerwear4", src:"../assets/outerwear/outerwear4.png", clothClass:"outerwear"},
            {id:"outerwear5", src:"../assets/outerwear/outerwear5.png", clothClass:"outerwear"},
            {id:"outerwear6", src:"../assets/outerwear/outerwear6.png", clothClass:"outerwear"},
            {id:"outerwear7", src:"../assets/outerwear/outerwear7.png", clothClass:"outerwear"},
            {id:"outerwear8", src:"../assets/outerwear/outerwear8.png", clothClass:"outerwear"},
            {id:"outerwear9", src:"../assets/outerwear/outerwear9.png", clothClass:"outerwear"},
            {id:"outerwear10", src:"../assets/outerwear/outerwear10.png", clothClass:"outerwear"},
            {id:"outerwear11", src:"../assets/outerwear/outerwear11.png", clothClass:"outerwear"},
            {id:"outerwear12", src:"../assets/outerwear/outerwear12.png", clothClass:"outerwear"},
            {id:"outerwear13", src:"../assets/outerwear/outerwear13.png", clothClass:"outerwear"},
            {id:"outerwear14", src:"../assets/outerwear/outerwear14.png", clothClass:"outerwear"},
            {id:"outerwear15", src:"../assets/outerwear/outerwear15.png", clothClass:"outerwear"},
            {id:"tops1", src:"../assets/tops/tops1.png", clothClass:"tops"},
            {id:"tops2", src:"../assets/tops/tops2.png", clothClass:"tops"},
            {id:"tops3", src:"../assets/tops/tops3.png", clothClass:"tops"},
            {id:"tops4", src:"../assets/tops/tops4.png", clothClass:"tops"},
            {id:"tops5", src:"../assets/tops/tops5.png", clothClass:"tops"},
            {id:"tops6", src:"../assets/tops/tops6.png", clothClass:"tops"},
            {id:"tops7", src:"../assets/tops/tops7.png", clothClass:"tops"},
            {id:"tops8", src:"../assets/tops/tops8.png", clothClass:"tops"},
            {id:"tops9", src:"../assets/tops/tops9.png", clothClass:"tops"},
            {id:"tops10", src:"../assets/tops/tops10.png", clothClass:"tops"},
            {id:"tops11", src:"../assets/tops/tops11.png", clothClass:"tops"},
            {id:"tops12", src:"../assets/tops/tops12.png", clothClass:"tops"},
            {id:"tops13", src:"../assets/tops/tops13.png", clothClass:"tops"},
            {id:"tops14", src:"../assets/tops/tops14.png", clothClass:"tops"},
            {id:"tops15", src:"../assets/tops/tops15.png", clothClass:"tops"},
            {id:"shoes1", src:"../assets/shoes/shoes1.png", clothClass:"shoes"},
            {id:"shoes2", src:"../assets/shoes/shoes2.png", clothClass:"shoes"},
            {id:"shoes3", src:"../assets/shoes/shoes3.png", clothClass:"shoes"},
            {id:"shoes4", src:"../assets/shoes/shoes4.png", clothClass:"shoes"},
            {id:"shoes5", src:"../assets/shoes/shoes5.png", clothClass:"shoes"},
            {id:"shoes6", src:"../assets/shoes/shoes6.png", clothClass:"shoes"},
            {id:"shoes7", src:"../assets/shoes/shoes7.png", clothClass:"shoes"},
            {id:"shoes8", src:"../assets/shoes/shoes8.png", clothClass:"shoes"},
            {id:"shoes9", src:"../assets/shoes/shoes9.png", clothClass:"shoes"},
            {id:"shoes10", src:"../assets/shoes/shoes10.png", clothClass:"shoes"},
            {id:"shoes11", src:"../assets/shoes/shoes11.png", clothClass:"shoes"},
            {id:"shoes12", src:"../assets/shoes/shoes12.png", clothClass:"shoes"},
            {id:"shoes13", src:"../assets/shoes/shoes13.png", clothClass:"shoes"},
            {id:"shoes14", src:"../assets/shoes/shoes14.png", clothClass:"shoes"},
            {id:"shoes15", src:"../assets/shoes/shoes15.png", clothClass:"shoes"},
        ]
        localStorage.setItem("cloth", JSON.stringify(cloth))
    }

    if (!localStorage.usersHarry) {
        const usersHarry  = [
            {username:"admin",
            email:"admin@email.com",
            password:"123",
            avatar:"../assets/avatar1.jpg",
            code: 1,
            isBlocked: false,
            pageLoad: "",
            clothLoad: "",
            favorites:[],
            following: [],
            followers: [],
            openAccount: ""
            },
        ]
        localStorage.setItem("usersHarry", JSON.stringify(usersHarry))
    }
}

// localStorage.clear()
// sessionStorage.clear()